#!/bin/bash

# 数据库安全规则上传脚本

echo "📋 数据库安全规则配置指南"
echo ""
echo "============================================"
echo "方法1: 腾讯云控制台上传（推荐）"
echo "============================================"
echo ""
echo "1. 打开数据库控制台："
echo "   https://tcb.cloud.tencent.com/dev?envId=cloud1-6gmp2q0y3171c353#/db/doc"
echo ""
echo "2. 点击左侧「数据库」→「安全规则」"
echo ""
echo "3. 点击「新建规则」或「编辑规则」"
echo ""
echo "4. 将 database.rules.json 的内容复制粘贴到编辑器"
echo ""
echo "5. 点击「保存」并确认"
echo ""
echo "============================================"
echo "方法2: 使用 CloudBase CLI 上传"
echo "============================================"
echo ""
echo "安装 CloudBase CLI（如果未安装）："
echo "   npm install -g @cloudbase/cloudbase-cli"
echo ""
echo "登录 CloudBase："
echo "   tcb login"
echo ""
echo "上传数据库规则："
echo "   tcb database:updateRules --file database.rules.json"
echo ""
echo "============================================"
echo "验证规则是否生效"
echo "============================================"
echo ""
echo "1. 在控制台点击「测试规则」"
echo ""
echo "2. 输入测试数据（例如 OPENID）"
echo ""
echo "3. 检查读写权限是否正确配置"
echo ""
echo "============================================"
echo "安全规则说明"
echo "============================================"
echo ""
echo "✅ users - 用户只能读写自己的数据"
echo "✅ reward_records - 只能读自己的奖励记录"
echo "✅ orders - 只能读写自己的订单"
echo "✅ promotion_orders - 买家和推广人可读"
echo "✅ products/categories/coupons - 所有人可读"
echo "❌ registration_attempts - 完全禁止访问"
echo "❌ operation_logs - 完全禁止访问"
echo ""
